### ISSUE TITLE
typo in first letter of az network commands, they require --vnet-name not VNet-name

### ISSUE THREAD

**Issue by ignaciofls** [jhirono/amlsecurity#2]
Shown: az network vnet subnet update -g $rg --VNet-name hub -n training --service-endpoints Microsoft.Storage Microsoft.KeyVault Microsoft.ContainerRegistry

correct: az network vnet subnet update -g $rg --vnet-name hub -n training --service-endpoints Microsoft.Storage Microsoft.KeyVault Microsoft.ContainerRegistry

Thanks

**Comment by jhirono** [comment]
Thanks I missed this comment but updated.
